server:
  port: 8081
  logback:
    log-filename: product
    root-level: DEBUG
    bussiness-dir: E:/
spring:
  profiles:
    active: test
#  zipkin:
#    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
#    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
#  sleuth:
#    sampler:
#      probability: 1.0 #采样的百分比
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.28.19.66:8066/DHOME?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: dhome
    password: dhome
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848