server:
  port: 8091
  tomcat:
    max-threads: 10
spring:
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.28.19.66:8066/DHOME?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: dhome
    password: dhome
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 9999 #跟控制台交流的端口,随意指定一个未使用的端口即可
        dashboard: localhost:8080 #指定控制台服务的地址
#      filter:
#        enabled: false

service-product: # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule