server:
  port: 8071
spring:
  application:
  name: service-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.28.19.66:8066/DHOME?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: dhome
    password: dhome
    jpa:
      hibernate:
        ddl-auto: update
      #show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect